<?php

namespace FragosoBundle\Repository;

/**
 * CommandeDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
