fragoso_homepage:
    path:     /
    defaults: { _controller: FragosoBundle:Home:index }
    
#######    Catalogue    ###############
catalogue_home:
    path: /catalogue
    defaults: { _controller: FragosoBundle:Catalogue:index }
 
## Categorie   
creer_categorie:
    path: /catalogue/categorie/edit
    defaults: { _controller: FragosoBundle:Catalogue:editerCategorie }

editer_categorie:
    path: /catalogue/categorie/edit/{categorie_num}
    defaults: { _controller: FragosoBundle:Catalogue:editerCategorie }
    requirements:
        categorie_num: \d+
        
supprimer_categorie:
    path: /catalogue/categorie/del/{categorie_num}
    defaults: { _controller: FragosoBundle:Catalogue:supprimerCategorie }
    requirements:
        categorie_num: \d+
        
## Articles
creer_article:
    path: /catalogue/article/edit
    defaults: { _controller: FragosoBundle:Catalogue:editerArticle }

editer_article:
    path: /catalogue/article/edit/{article_num}
    defaults: { _controller: FragosoBundle:Catalogue:editerArticle }
    requirements:
        article_num: \d+


##########   Commandes   ############
commande_home:
    path: /commande
    defaults: { _controller: FragosoBundle:Commande:index }

lister_commande:
    path: /commande/liste/{commande_etat}
    defaults: { _controller: FragosoBundle:Commande:listerCommande }

creer_commande:
    path: /client/{client_num}/commande/edit
    defaults: { _controller: FragosoBundle:Commande:editerCommande }
    requirements:
        client_num: \d+

editer_commande:
    path: /client/{client_num}/commande/edit/{commande_num}
    defaults: { _controller: FragosoBundle:Commande:editerCommande }
    requirements:
        client_num: \d+
        commande_num: \d+

supprimer_commande:
    path: /catalogue/commande/del/{commande_num}
    defaults: { _controller: FragosoBundle:Commande:supprimerCommande }
    requirements:
        commande_num: \d+
        
creer_paiement:
    path: /client/{client_num}/commande/{commande_num}/paiement
    defaults: { _controller: FragosoBundle:Commande:payerCommande }
    requirements:
        client_num: \d+
        commande_num: \d+

terminer_commande:
    path: /commande/{commande_num}/terminer
    defaults: { _controller: FragosoBundle:Commande:terminerCommande }
    requirements:
        commande_num: \d+

generer_facture:
    path: /commande/facture/{commande_num}
    defaults: { _controller: FragosoBundle:Commande:genererFacture }
    requirements:
        commande_num: \d+

##########   Clients    #############
client_home:
    path: /client
    defaults: { _controller: FragosoBundle:Client:index }

creer_client:
    path: /client/edit
    defaults: { _controller: FragosoBundle:Client:editerClient }
   
editer_client:
    path: /client/edit/{client_num}
    defaults: { _controller: FragosoBundle:Client:editerClient }
    requirements:
        client_num: \d+

supprimer_client:
    path: /client/del/{client_num}
    defaults: { _controller: FragosoBundle:Client:supprimerClient }
    requirements:
        client_num: \d+

afficher_client:
    path: /client/detail/{client_num}
    defaults: { _controller: FragosoBundle:Client:afficherClient }
    requirements:
        client_num: \d+
